name: Check Conformance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - uses: astral-sh/ruff-action@v4.0.0
    - name: Test with unittest
      run: |
        python -m unittest discover
